### ISSUE TITLE
Set up frontend tooling

### ISSUE THREAD

**Issue by tomodwyer** [opensafely-core/output-explorer#34]
So that we can build styles and scripts using modern tools.

## Todo

- [x] Set up [Vite](https://vitejs.dev/)
- [x] Integrate with Django via [Whitenoise](https://whitenoise.evans.io/en/stable/)
- [x] Deploy with GitHub Actions
- [x] Local development story and documentation
